#!/usr/bin/env python3
"""Fan-out with dynamic team generation.

Combines two HiveFlow capabilities:

  1. **Team Generation** -- ``TeamGenerator`` dynamically selects agent
     archetypes and wires a workflow from a task description alone.
  2. **Parallel Fan-Out** -- when the generated team includes a planner
     (orchestrator) followed by a worker, the workflow is automatically
     wired as orchestrator -> parallel_fan_out -> assembly.

The result is a fully parallel divide-and-conquer pipeline with **zero
manual agent or workflow construction**.

Usage:
  uv run python examples/fan_out_generated.py
  uv run python examples/fan_out_generated.py --task "Compare 5 programming languages for web development"
  uv run python examples/fan_out_generated.py --no-review
"""

import argparse
import asyncio
import json
import logging
import os
import re
import sys
import time
from datetime import datetime
from pathlib import Path
from typing import Any

# Ensure hiveflow is importable when running from repo root
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from hiveflow import TeamGenerator
from hiveflow.plugins.llm.openai_provider import OpenAIProvider

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
DEFAULT_BASE_URL = os.environ.get("OPENAI_BASE_URL", "http://localhost:8080/v1")
MODEL_NAME = "local-model"

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger("fan_out_generated")


# ---------------------------------------------------------------------------
# Event handler
# ---------------------------------------------------------------------------
_step_start_times: dict[str, float] = {}


def on_event(event_type: str, agent_id: str, data: dict[str, Any]) -> None:
    """Log workflow events with timing."""
    if event_type == "step_start":
        _step_start_times[agent_id] = time.time()
        logger.info("=" * 60)
        logger.info("STEP START: %s (%s)", agent_id, data.get("step_type", ""))
        logger.info("=" * 60)
    elif event_type == "step_complete":
        elapsed = time.time() - _step_start_times.get(agent_id, time.time())
        logger.info("STEP COMPLETE: %s (%.1fs)", agent_id, elapsed)
    elif event_type == "step_error":
        logger.error("STEP ERROR: %s -- %s", agent_id, data.get("error", "unknown"))
    elif event_type == "summary_generated":
        logger.info(
            "  Summary for %s (%s words)",
            agent_id, data.get("summary_length", "?"),
        )
    elif event_type == "outline_generated":
        logger.info(
            "  Outline for %s (%s items)",
            agent_id, data.get("num_items", "?"),
        )
    elif event_type == "assembly_complete":
        logger.info(
            "  Assembly: %s sections, %s words",
            data.get("num_sections", "?"), data.get("total_words", "?"),
        )


# ---------------------------------------------------------------------------
# Markdown output
# ---------------------------------------------------------------------------
def _slugify(text: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return slug[:80]


def write_report(
    task: str,
    config: dict[str, Any],
    result_state: dict[str, Any],
    output_dir: Path,
) -> Path:
    """Write assembled output to a markdown file."""
    output_dir.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    filepath = output_dir / f"{timestamp}-{_slugify(task)}.md"

    final_output = result_state.get("final_output", "")
    parallel_items = result_state.get("parallel_items", [])

    lines = [
        f"# {task}",
        "",
        f"*Generated by HiveFlow (fan-out + team generation) on "
        f"{datetime.now().strftime('%Y-%m-%d %H:%M')}*",
        "",
        f"**Sections:** {len(parallel_items)}  ",
        f"**Word count:** {len(final_output.split()) if final_output else 0}",
        "",
        "---",
        "",
        "## Generated Team Configuration",
        "",
        "```json",
        json.dumps(config, indent=2),
        "```",
        "",
        "---",
        "",
    ]

    # Table of contents from parallel items
    if parallel_items:
        lines.append("## Table of Contents")
        lines.append("")
        for i, item in enumerate(parallel_items, 1):
            lines.append(f"{i}. {item}")
        lines.append("")
        lines.append("---")
        lines.append("")

    # Assembled body
    if final_output:
        lines.append(final_output)
        lines.append("")

    filepath.write_text("\n".join(lines), encoding="utf-8")
    return filepath


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
async def run(task: str, base_url: str, output_dir: Path, include_review: bool) -> None:
    start_time = time.time()

    # -- Step 1: Generate team with fan-out ------------------------------------
    #   planner (orchestrator) -> writer (parallel_fan_out) [-> reviewer]
    generator = TeamGenerator()
    config = generator.generate_team(
        task_description=task,
        agent_types=["planner", "writer"],
        include_review=include_review,
    )

    logger.info("Task: %s", task)
    logger.info("Generated team: %s", config["team_name"])
    logger.info("  Agents: %s", [a["id"] for a in config["agents"]])
    flow = " -> ".join(
        f'{s["agent"]} ({s["type"]})'
        for s in config["workflow"]["steps"]
    )
    logger.info("  Workflow: %s", flow)
    logger.info("")
    logger.info("Config:\n%s", json.dumps(config, indent=2))
    logger.info("")

    # -- Step 2: Build and execute ---------------------------------------------
    provider = OpenAIProvider(base_url=base_url, api_key="not-needed")
    agents, engine = generator.build(config, provider, model=MODEL_NAME)
    engine.on_event(on_event)

    result = await engine.execute(
        agents=agents,
        initial_state={"task": task},
    )

    elapsed = time.time() - start_time

    # -- Step 3: Log results ---------------------------------------------------
    logger.info("")
    logger.info("=" * 60)
    logger.info("WORKFLOW COMPLETE")
    logger.info("=" * 60)
    logger.info("  Status:  %s", result.status.value)
    logger.info("  Steps:   %d", len(result.step_results))
    logger.info("  Elapsed: %.1fs", elapsed)

    if result.error:
        logger.error("  Error: %s", result.error)
        return

    # Parallel item details
    parallel_items = result.state.get("parallel_items", [])
    writer_outputs = result.state.get("writer_outputs", [])
    logger.info("  Items planned:  %d", len(parallel_items))
    logger.info("  Items written:  %d", len(writer_outputs))

    for i, item in enumerate(parallel_items):
        output = writer_outputs[i] if i < len(writer_outputs) else ""
        words = len(output.split()) if isinstance(output, str) else 0
        logger.info("    %d. %d words -- %s", i + 1, words, item[:60])

    # Token usage
    logger.info("")
    logger.info("Token usage:")
    total_tokens = 0
    for step in result.step_results:
        usage = result.state.get(f"{step.agent_id}_usage")
        if usage:
            logger.info(
                "  %s: %d tokens (prompt=%d, completion=%d)",
                step.agent_id,
                usage["total_tokens"],
                usage["prompt_tokens"],
                usage["completion_tokens"],
            )
            total_tokens += usage["total_tokens"]
    logger.info("  Total: %d tokens", total_tokens)

    # -- Step 4: Write markdown ------------------------------------------------
    final = result.state.get("final_output", "")
    filepath = write_report(task, config, result.state, output_dir)
    word_count = len(final.split()) if final else 0
    logger.info("")
    logger.info("Report written: %s (%d words)", filepath, word_count)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Fan-out pipeline with dynamic team generation",
    )
    parser.add_argument(
        "--task",
        default=(
            "Write a comprehensive analysis of renewable energy technologies "
            "and their impact on global energy markets"
        ),
        help="Task description",
    )
    parser.add_argument(
        "--base-url",
        default=DEFAULT_BASE_URL,
        help="OpenAI-compatible API base URL",
    )
    parser.add_argument(
        "--output-dir",
        default="output",
        help="Directory for the markdown output (default: ./output)",
    )
    parser.add_argument(
        "--no-review",
        action="store_true",
        help="Skip the reviewer step",
    )
    args = parser.parse_args()
    asyncio.run(
        run(
            task=args.task,
            base_url=args.base_url,
            output_dir=Path(args.output_dir),
            include_review=not args.no_review,
        )
    )


if __name__ == "__main__":
    main()
