#!/usr/bin/env python3
"""Dynamic team generation -- the "Generation mode" fallback.

When no pre-built team template exists for a task, HiveFlow can dynamically
compose a team from agent archetypes.  This example demonstrates that path:

  1. The user provides only a **task description** (no JSON config, no
     predefined agents or workflow).
  2. ``TeamGenerator`` selects appropriate agent archetypes and wires a
     workflow automatically.
  3. ``TeamGenerator.build()`` creates live agents and a workflow engine
     (with summary propagation and assembly wired automatically).
  4. Results are written to a markdown file.

This is the fallback described in the v2 requirements:

  *"When no pre-built template exists for a given task, ask the LLM to
  generate one ... The LLM returns a structured team definition that the
  framework can execute."*

  Here we use archetype-based generation (no LLM call needed for the config
  itself), which is fast and deterministic.

Usage:
  uv run python examples/generated_team.py
  uv run python examples/generated_team.py --task "Write a legal contract review for a SaaS agreement"
  uv run python examples/generated_team.py --task "Create a marketing plan for a new product launch" --no-review
"""

import argparse
import asyncio
import json
import logging
import os
import re
import sys
import time
from datetime import datetime
from pathlib import Path
from typing import Any

# Ensure hiveflow is importable when running from repo root
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from hiveflow import TeamGenerator
from hiveflow.plugins.llm.openai_provider import OpenAIProvider

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
DEFAULT_BASE_URL = os.environ.get("OPENAI_BASE_URL", "http://localhost:8080/v1")
MODEL_NAME = "local-model"

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger("generated_team")


# ---------------------------------------------------------------------------
# Event handler
# ---------------------------------------------------------------------------
_step_start_times: dict[str, float] = {}


def on_event(event_type: str, agent_id: str, data: dict[str, Any]) -> None:
    """Log workflow events."""
    if event_type == "step_start":
        _step_start_times[agent_id] = time.time()
        logger.info("=" * 60)
        logger.info("STEP START: %s (%s)", agent_id, data.get("step_type", ""))
        logger.info("=" * 60)
    elif event_type == "step_complete":
        elapsed = time.time() - _step_start_times.get(agent_id, time.time())
        logger.info("STEP COMPLETE: %s (%.1fs)", agent_id, elapsed)
    elif event_type == "step_error":
        logger.error("STEP ERROR: %s -- %s", agent_id, data.get("error", "unknown"))
    elif event_type == "summary_generated":
        logger.info(
            "  Summary generated for %s (%s words)",
            agent_id, data.get("summary_length", "?"),
        )
    elif event_type == "assembly_complete":
        logger.info(
            "  Assembly complete: %s sections, %s words",
            data.get("num_sections", "?"), data.get("total_words", "?"),
        )


# ---------------------------------------------------------------------------
# Markdown output
# ---------------------------------------------------------------------------
def _slugify(text: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return slug[:80]


def write_report(
    task: str,
    config: dict[str, Any],
    result_state: dict[str, Any],
    output_dir: Path,
) -> Path:
    """Write the generated config and workflow output to a markdown file."""
    output_dir.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    slug = _slugify(task)
    filepath = output_dir / f"{timestamp}-{slug}.md"

    final_output = result_state.get("final_output", "")
    agent_ids = [a["id"] for a in config["agents"]]

    lines = [
        f"# {task}",
        "",
        f"*Generated by HiveFlow (generation mode) on "
        f"{datetime.now().strftime('%Y-%m-%d %H:%M')}*",
        "",
        "---",
        "",
        "## Generated Team Configuration",
        "",
        "```json",
        json.dumps(config, indent=2),
        "```",
        "",
        "---",
        "",
    ]

    # Per-agent outputs
    for agent_id in agent_ids:
        output = result_state.get(f"{agent_id}_output", "")
        if output:
            words = len(output.split())
            lines.append(f"## {agent_id} ({words} words)")
            lines.append("")
            lines.append(output)
            lines.append("")
            lines.append("---")
            lines.append("")

    # Assembled final output
    if final_output:
        lines.append("## Final Assembled Output")
        lines.append("")
        lines.append(f"**Word count:** {len(final_output.split())}")
        lines.append("")
        lines.append(final_output)
        lines.append("")

    filepath.write_text("\n".join(lines), encoding="utf-8")
    return filepath


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
async def run(task: str, base_url: str, output_dir: Path, include_review: bool) -> None:
    start_time = time.time()

    # -- Step 1: Generate team config dynamically ------------------------------
    generator = TeamGenerator()
    config = generator.generate_team(
        task_description=task,
        include_review=include_review,
    )

    logger.info("Task: %s", task)
    logger.info("")
    logger.info("Generated team: %s", config["team_name"])
    logger.info("  Agents: %s", [a["id"] for a in config["agents"]])
    workflow_steps = config["workflow"]["steps"]
    flow = " -> ".join(
        s["agent"] + (" (conditional)" if s["type"] == "conditional" else "")
        for s in workflow_steps
    )
    logger.info("  Workflow: %s", flow)
    logger.info("")
    logger.info("Full config:")
    logger.info("%s", json.dumps(config, indent=2))
    logger.info("")

    # -- Step 2: Build live agents and workflow --------------------------------
    #   build() handles: behavior-type fallback (tool_user -> llm_only),
    #   SummaryGenerator wiring, and code-level assembly for writer agents.
    provider = OpenAIProvider(base_url=base_url, api_key="not-needed")
    agents, engine = generator.build(config, provider, model=MODEL_NAME)
    engine.on_event(on_event)

    # -- Step 3: Execute -------------------------------------------------------
    result = await engine.execute(
        agents=agents,
        initial_state={"task": task},
    )

    elapsed = time.time() - start_time

    # -- Step 4: Log results ---------------------------------------------------
    logger.info("")
    logger.info("=" * 60)
    logger.info("WORKFLOW COMPLETE")
    logger.info("=" * 60)
    logger.info("  Status:  %s", result.status.value)
    logger.info("  Steps:   %d", len(result.step_results))
    logger.info("  Elapsed: %.1fs", elapsed)

    if result.error:
        logger.error("  Error: %s", result.error)
        return

    for step in result.step_results:
        output = result.state.get(f"{step.agent_id}_output", "")
        words = len(output.split()) if isinstance(output, str) else 0
        logger.info("  %s: %d words", step.agent_id, words)

    # Token usage
    logger.info("")
    logger.info("Token usage:")
    total_tokens = 0
    for step in result.step_results:
        usage = result.state.get(f"{step.agent_id}_usage")
        if usage:
            logger.info(
                "  %s: %d tokens (prompt=%d, completion=%d)",
                step.agent_id,
                usage["total_tokens"],
                usage["prompt_tokens"],
                usage["completion_tokens"],
            )
            total_tokens += usage["total_tokens"]
    logger.info("  Total: %d tokens", total_tokens)

    # -- Step 5: Write markdown ------------------------------------------------
    final = result.state.get("final_output", "")
    filepath = write_report(task, config, result.state, output_dir)
    word_count = len(final.split()) if final else 0
    logger.info("")
    logger.info("Report written: %s (%d words)", filepath, word_count)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Dynamically generate a team and execute a workflow (generation mode)",
    )
    parser.add_argument(
        "--task",
        default="Analyze the pros and cons of remote work and write a balanced policy recommendation",
        help="Task description (no predefined config needed)",
    )
    parser.add_argument(
        "--base-url",
        default=DEFAULT_BASE_URL,
        help="OpenAI-compatible API base URL",
    )
    parser.add_argument(
        "--output-dir",
        default="output",
        help="Directory for the generated markdown report (default: ./output)",
    )
    parser.add_argument(
        "--no-review",
        action="store_true",
        help="Skip the reviewer step",
    )
    args = parser.parse_args()
    asyncio.run(
        run(
            task=args.task,
            base_url=args.base_url,
            output_dir=Path(args.output_dir),
            include_review=not args.no_review,
        )
    )


if __name__ == "__main__":
    main()
